### ISSUE TITLE
Problem running on wlroots

### ISSUE THREAD

**Issue by pm4rcin** [flathub/io.github.fabiangreffrath.Doom#9]
Hi, thanks for bringing that port to flatpak! However I have a problem which is that the game window doesn't show on screen even though the sound is playing and game uses CPU. It's because old version of SDL is shipped. The issue was resolved on chocolate-doom by updating runtime. See https://github.com/flathub/org.chocolate_doom.ChocolateDoom/commit/7d8834ee9f4d3145498b79ff4f344e802f8d756e
`xdg_surface@29: error -1: Tried to set invalid xdg-surface geometry`
wlroots: 0.15.1
compositor: dwl
CPU: Ryzen 5 4600H (I've used integrated graphics)

**Comment by davidarnold** [comment]
Thanks for the bug report!  Given that this is related to a niche compositor (no offense intended) this won't be very easy for me to reproduce.  I have no problem bumping the platform runtime version since I would do that eventually anyway, but I'd rather not pull in those SDL overrides unless I have test results to prove they are necessary.

Even if I don't find time to test, I will make sure to bump the platform version in the next release of Crispy Doom.  To set expectations based on history, that could take up to a few months for a new upstream release.

FWIW, Crispy runs fine on Wayland for me under Fedora / Gnome.  It might be worth reporting this to either wlroots or dwl to see if there is something that needs to be fixed there.

**Comment by pm4rcin** [comment]
Looks like sdl2 is on 2.24 on freedesktop 22.08. Also mixer has the same version that is present on freedesktop and the sdl2-net 2.2.0 the only change is support for cmake so overrides are not necessary. Thanks for pointing that out, I'll report it to chocolate-doom flatpak maintainer.

So would you update the runtime maybe on beta branch? I could test if it's working normally and then you would either merge to stable or leave it here until next release of crispy.

**Comment by davidarnold** [comment]
@pm4rcin I just released Crispy 6.0 on the 22.08 platform today.  Can you test and see if this fixes your issue?  Thanks!

**Comment by pm4rcin** [comment]
I have tested today on sway but I assume that it should be identical since the base is the same. If problem arises again I'll reopen. Thanks! :)
